#server:
#  port: 4444
#spring:
#  application:
#    name: apigateway
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/
#zuul:
#  routes:
#    punishment:
#      path: /punishment/**
#      serviceId: punishmentservice
#      url: http://localhost:2222
