server:
  port: 1111
spring:
  application:
    name: eurekaserver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true