server:
  port: 1111
spring:
  application:
    name: eureka-server
eureka:
  client:
    #是否从服务注册中心检索服务实例
    fetch-registry: false
    #是否将自身注册到注册中心
    register-with-eureka: false
    #服务注册中心地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #主机名称
  instance:
    hostname: localhost
    prefer-ip-address: true