server:
  port: 1111
spring:
  application:
    name: eurekaserver
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/