server:
  port: 2222
spring:
  application:
    name: punishment-service
eureka:
  client:
    serviceUrl:
      #服务注册中心地址
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true