server:
  port: 5555
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/weixiaohuai/config-server.git
#          search-paths: repository
#          username: xxx
#          password: xxx
          default-label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/