server:
  port: ${port:5555}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${gitRepositoryUrl:https://gitee.com/weixiaohuai/config-server.git}
          default-label: master
eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekaServerUrl:http://localhost:1111/eureka/}
  instance:
    ip-address: ${ipAddress:127.0.0.1}
    prefer-ip-address: true